#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export NODE_ENV=production

HOME=/config exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1337" \
    cd /app s6-setuidgid abc node app.js --prod "$@"
