name: Build Image On Release

on:
  workflow_dispatch:
  release:
    types: [ published ]
  pull_request:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-image.yml@v7
    with:
      repo_owner: "thespad"
      app_name: "planka"
      release_type: "github"
      release_url: "https://api.github.com/repos/plankanban/planka"
      dockerhub_user: "thespad"
      target-arch: "64"
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
