name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-image.yml@v8.0.0
    with:
      repo_owner: "thespad"
      app_name: "planka"
      release_type: "github"
      release_url: "https://api.github.com/repos/plankanban/planka"
      dockerhub_user: "thespad"
      target-arch: "64"
      sign_image: false
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
